name: disposable_provider
description: DisposableProvider is thin wrapper of Provider and it calls dispose automatically.
version: 2.4.0
homepage: https://github.com/mono0926/disposable_provider
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: '>=6.0.0 <7.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
